all:
	$(MAKE) -C src

clean:
	$(MAKE) -C src clean

help:
	@echo "\nUsage:\n"
	@echo "make [all]:	Build 4 binaries: commitment_gen, sign, prover, verifier."
	@echo "		Please read README.md or use '-h/--help' option on each binary for more information.\n"
	@echo "make clean:	Remove all files generated by make.\n"
	@echo "make help:	Display this help.\n"
